config/routes.rb
Rails.application.routes.draw do
  get 'taggings/new'
  resources :gardens, only: [:index, :show] do
    resources :plants, only: [:new, :create]
  end

  resources :plants, only: :destroy do
    resources :taggings, only: [:new, :create]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/garden.rb
class Garden < ApplicationRecord
  has_many :plants
end

app/models/plant.rb
class Plant < ApplicationRecord
  belongs_to :garden
  has_many :taggings
  has_many :tags, through: :taggings

  validates :name, presence: true, uniqueness: true
  validates :image_url, presence: true
end

app/models/tag.rb
class Tag < ApplicationRecord
  has_many :taggings
  has_many :plants, through: :taggings

  validates :name, presence: true, uniqueness: true
end

app/models/tagging.rb
class Tagging < ApplicationRecord
  belongs_to :plant
  belongs_to :tag

  validates :tag, uniqueness: { scope: :plant }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/gardens_controller.rb
class GardensController < ApplicationController
  before_action :set_garden, only: [:show, :edit, :update, :destroy]

  def index
    @gardens = Garden.all
  end

  def show
  end

  private
    def set_garden
      @garden = Garden.find(params[:id])
    end

    def garden_params
      params.require(:garden).permit(:name, :banner_image_url)
    end
end

app/controllers/plants_controller.rb
class PlantsController < ApplicationController
  def new
    @garden = Garden.find(params[:garden_id])
    @plant = Plant.new
  end

  def create
    @garden = Garden.find(params[:garden_id])
    @plant = Plant.new(plant_params)
    @plant.garden = @garden
    if @plant.save
      redirect_to @garden
    else
      render :new
    end
  end

  def destroy
    @plant = Plant.find(params[:id])
    @plant.destroy
    redirect_to @plant.garden
  end

  private

  def plant_params
    params.require(:plant).permit(:name, :image_url)
  end
end

app/controllers/taggings_controller.rb
class TaggingsController < ApplicationController
  def new
     # Could be in a set_plant before_action, since it also appear on #create
    @plant = Plant.find(params[:plant_id])

    @tagging = Tagging.new
  end

  def create
    # Could be in a set_plant before_action, since it also appear on #new
    @plant = Plant.find(params[:plant_id])

    # The method tag_ids returns an array of ids selected by the user, ::where
    # from active record accepts arrays also. So we can just use them here to
    # get all tags of the selected ids.
    @tags = Tag.where(id: tag_ids)

    # We build the tags that we want to save into an array of taggings
    taggings = @tags.map do |tag|
      Tagging.new(plant: @plant, tag: tag)
    end

    # We checked whether all tags we're able to be saved
    if taggings.all?(&:save)
      # If yes, we proceed as normal.
      redirect_to @plant.garden
    else
      # If not, we put the first failing tagging in this variable to show the
      # form errors to the user.
      @tagging = taggings.find { |tagging| tagging.errors.any? }
      render :new
    end
  end

  private

  def tagging_params
    # Strong params variations:
    # Note: We ended up moving away from this. But I left it here for reference.

    # For a string (most common by far)  👇
    # params.require(:tagging).permit(:tag_id)

    # For an array                       👇
    # params.require(:tagging).permit(tag_id: [])
  end

  def tag_ids
    # The fact that we are using a for for a tagging to create multiple taggings
    # makes it clunky that we have an array of multiple ids in a key named tag_id
    # I preferered to hide this under this method that has a pluralized name:
    # tag_ids
    params[:tagging][:tag_id]

    # Note: the clunky reject blank isn't necessary anymore because of the
    # include_hidden: false on the form. Check the taggings#new view.
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/taggings_helper.rb
module TaggingsHelper
end

app/views/gardens/_banner.html.erb
<div class="banner mb-4"
     style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(<%= garden.banner_image_url %>);
">
  <div class="container">
    <h1><%= garden.name %></h1>
  </div>
</div>

app/views/gardens/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Gardens</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Banner image url</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @gardens.each do |garden| %>
      <tr>
        <td><%= garden.name %></td>
        <td><%= garden.banner_image_url %></td>
        <td><%= link_to 'Show', garden %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/gardens/show.html.erb
<%= render 'banner', garden: @garden %>

<div class="container">
  <div class="row">
    <% @garden.plants.each do |plant| %>
      <div class="col-4">
        <%= render 'plants/card', plant: plant %>
      </div>
    <% end %>
    <div class="col-4">
      <%= link_to new_garden_plant_path(@garden), class: 'card-trip' do %>
        <img src="https://place-hold.it/320x240/a00/fff/?text=Add%20New%20Plant" />
        <div class="card-trip-infos">
          <div>
            <h2>Add New Plant</h2>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ParksAndPlants</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/plants/_card.html.erb
<div class="card-trip">
  <img src="<%= plant.image_url %>" />
  <div class="card-trip-infos">
    <div>
      <h2><%= plant.name %></h2>
      <div>
        <% plant.tags.each do |tag| %>
          <span class="badge badge-light"><%= tag.name %></span>
        <% end %>
        <%= link_to 'Add tag', new_plant_tagging_path(plant), class: 'badge badge-primary' %>
      </div>
      <%= link_to 'Delete', plant_path(plant), method: :delete, 'data-confirm': 'Are you sure?' %>
    </div>
  </div>
</div>

app/views/plants/new.html.erb
<div class="row justify-content-center">
  <div class="col-4">
    
    <%= simple_form_for [@garden, @plant] do |form| %>
      <%= form.input :name %>
      <%= form.input :image_url %>
      <%= form.button :submit, class: 'btn btn-primary' %>
    <% end %>
  </div>
</div>

app/views/taggings/new.html.erb
<div class="row justify-content-center">
  <div class="col-4">
      <%= simple_form_for [@plant, @tagging] do |form| %>
        <%= form.association :tag,
                             # Include hidden!!! That's the option that removes
                             # the blank string from the selection
                             include_hidden: false,
                             input_html: { multiple: true }%>
        <%= form.button :submit, class: 'btn btn-primary' %>
      <% end %>
  </div>
</div>